version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm_automation_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
    command: celery -A src.tasks.celery_app worker --loglevel=info

  beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
    command: celery -A src.tasks.celery_app beat --loglevel=info

volumes:
  postgres_data_dev:
  redis_data_dev:
